title: Mohammad Monfared's CV
description:  Resume
url: http://monfared.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
